### ISSUE TITLE
Save video with system  Audio using this sample.

### ISSUE THREAD

**Issue by aqibbanday** [robmikh/WPFCaptureSample#4]
Do you have a sample where i can save audio with this capture sample.

**Comment by robmikh** [comment]
Unfortunately that's currently out of scope for this sample. This sample is mainly focused on the graphics side of things. I'd suggest lookup up WASAPI if you'd like to do [loopback recording](https://docs.microsoft.com/en-us/windows/win32/coreaudio/loopback-recording).
